<a href="https://colab.research.google.com/github/MURALAAYYAPPA/Machine-Learning/blob/main/K_Fold_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [8]:
lr = LogisticRegression(max_iter=1000) # Increased max_iter to prevent ConvergenceWarning
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9592592592592593

In [9]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9814814814814815

In [10]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9703703703703703

In [12]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [13]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [14]:
def get_score(model, X_train, X_test, y_train, y_test):
  model.fit(X_train, y_train)
  return model.score(X_test, y_test)

In [19]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [15]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9814814814814815

In [16]:
get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)


0.975925925925926

In [18]:
get_score(LogisticRegression(max_iter=1000), X_train, X_test, y_train, y_test)

0.9592592592592593

In [26]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
  x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
  scores_lr.append(get_score(LogisticRegression(max_iter=1000), x_train, x_test, y_train, y_test))
  scores_svm.append(get_score(SVC(), x_train, x_test, y_train, y_test))
  scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))


In [27]:
scores_lr

[0.9198664440734557, 0.9415692821368948, 0.9165275459098498]

In [28]:
scores_rf

[0.9265442404006677, 0.9449081803005008, 0.9198664440734557]

In [29]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [30]:
from sklearn.model_selection import cross_val_score

In [31]:
cross_val_score(LogisticRegression(max_iter=1000), digits.data, digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [32]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [34]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.93333333, 0.89166667, 0.95821727, 0.95821727, 0.91922006])